# .github/workflows/build.yml

name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 'Building...'
      uses: peaceiris/actions-gh-pages@v3
      env:
        DEPLOY_REPO: shvinq/shvinq.github.io
        DEPLOY_BRANCH: master
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Shanghai