# .github/workflows/build.yml

name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: windows10

    steps:
    - name: 'Building...'
      uses: shvinq/hugo-deploy@v1
      env:
        DEPLOY_REPO: Shvinq/shvinq.github.io
        DEPLOY_BRANCH: build
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
        TZ: Asia/Hangzhou